### ISSUE TITLE
Config parser

### ISSUE THREAD

**Issue by tomofuji-dev** [tomofuji-dev/ft_webserv_playground#8]
## Overview
サーバーconfigのパース

## Task
- [x] クラス変数の列挙
- [x] nginxのconfigを確認
- [x] パーサー

## 課題文configuration fileの指定
- [ ] Choose the port and host of each ’server’.
- [ ] Setup the server_names or not.
- [ ] The first server for a host:port will be the default for this host:port (that means it will answer to all the requests that don’t belong to an other server).
- [ ] Setup default error pages
- [ ] Limit client body size.
- [ ] Setup routes with one or multiple of the following rules/configuration (routes wont be using regexp):
- [ ] Define a list of accepted HTTP methods for the route.
- [ ] Define a HTTP redirection
- [ ] Define a directory or a file from where the file should be searched 
- [ ] Turn on or off directory listing
- [ ] Set a default file to answer if the request is a directory.
- [ ] Execute CGI based on certain file extension 
- [ ] Make it work with POST and GET methods.
- [ ] Make the route able to accept uploaded files and configure where they should be saved.

**Comment by tomofuji-dev** [comment]
- []

**Comment by tomofuji-dev** [comment]
https://github.com/JUNNETWORKS/42-webserv/blob/main/docs/configuration.md

**Comment by tomofuji-dev** [comment]
Turn on or off directory listingがよくわからん

**Comment by tomofuji-dev** [comment]
Turn on or off directory listing: autoindex on;

**Comment by tomofuji-dev** [comment]
validatorの見直しが必要
